name: Workflow for CI
on:
  push:
    branches:
      - main
jobs:
  run-pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade-strategy=only-if-needed
      - name: Install Dependencies
        run: |
          pipenv install --dev -e .
      - name: Run pytest
        run: |
          pipenv run pytest
